import {redirect} from 'next/navigation';
import {getSession} from '@/lib/session';
import {adminDb} from '@/lib/db';
import {safeQuery} from '@/lib/safe-db';
import {Shell} from '@/components/shell';
export default async function MyDashboard(){
 const s=await getSession();if(!s)redirect('/login');const db=adminDb();
 const [profile,payouts,warnings,joins]=await Promise.all([
  safeQuery(db.from('registrations').select('*').eq('discord_id',s.id).maybeSingle(),null as any),
  safeQuery(db.from('payouts').select('*').eq('discord_id',s.id).order('created_at',{ascending:false}),[] as any[]),
  safeQuery(db.from('warnings').select('*').eq('discord_id',s.id).eq('status','active').order('created_at',{ascending:false}),[] as any[]),
  safeQuery(db.from('event_participants').select('joined_at,attendance_status,event_runs(status,scheduled_start,event_templates(name))').eq('discord_id',s.id).order('joined_at',{ascending:false}).limit(10),[] as any[])
 ]);
 const open=payouts.data.filter((p:any)=>p.status==='open');const sum=open.reduce((a:number,p:any)=>a+Number(p.amount||0),0);const points=warnings.data.reduce((a:number,w:any)=>a+Number(w.points||0),0);
 return <Shell title={`Willkommen, ${s.username}`} subtitle="Dein persönlicher Nythera-Bereich"><section className="heroMember"><div><span className="eyebrow">MEMBER DASHBOARD</span><h2>{profile.data?`${profile.data.first_name} ${profile.data.last_name}`:s.username}</h2><p>{profile.data?`Ingame-ID ${profile.data.ingame_id}`:'Deine Registrierung wurde noch nicht vollständig gefunden.'}</p></div><div className="memberStatus"><span className="pill green">{profile.data?.status||'Discord verbunden'}</span></div></section><section className="stats"><div className="stat"><div className="statLabel">Offene Auszahlung</div><div className="statValue">{sum.toLocaleString('de-DE')}$</div><div className="statHint">{open.length} offene Posten</div></div><div className="stat"><div className="statLabel">Verwarnpunkte</div><div className="statValue">{points}</div><div className="statHint">{warnings.data.length} aktive Verwarnungen</div></div><div className="stat"><div className="statLabel">Event-Anmeldungen</div><div className="statValue">{joins.data.length}</div><div className="statHint">Letzte 10 Einträge</div></div><div className="stat"><div className="statLabel">Zugriff</div><div className="statValue smallValue">{s.access}</div><div className="statHint">Über Discord-Rolle geprüft</div></div></section><div className="grid2"><section className="card"><div className="cardHead"><div><h2>Meine Events</h2><p>Deine letzten Anmeldungen</p></div></div><div className="eventList">{joins.data.length?joins.data.map((j:any,i:number)=><div className="eventRow" key={i}><div><div className="eventName">{j.event_runs?.event_templates?.name||'Event'}</div><div className="eventMeta">{j.event_runs?.scheduled_start?new Date(j.event_runs.scheduled_start).toLocaleString('de-DE'):'Manuell'}</div></div><span className="pill blue">{j.attendance_status}</span></div>):<div className="empty">Noch keine Event-Anmeldungen.</div>}</div></section><section className="card"><div className="cardHead"><div><h2>Meine Auszahlungen</h2><p>Nur deine eigenen Einträge</p></div></div><div className="eventList">{payouts.data.length?payouts.data.slice(0,8).map((p:any)=><div className="eventRow" key={p.id}><div><div className="eventName">{Number(p.amount).toLocaleString('de-DE')}$</div><div className="eventMeta">{new Date(p.created_at).toLocaleDateString('de-DE')}</div></div><span className={`pill ${p.status==='completed'?'green':'blue'}`}>{p.status}</span></div>):<div className="empty">Keine Auszahlungen vorhanden.</div>}</div></section></div></Shell>
}
